### PR TITLE
SQLAlchemy models for MCH

### PR DESCRIPTION
**Pull request by faysal-ishtiaq**
I encountered an error while importing the tables into the database. In the DDL file on line 506, it was
```sql
CREATE TABLE Recepsping (
......
    Datee datetime NOT NULL default "0000-00-00 00:00:00",
......
```
I changed it to the following to solve the error
```sql
CREATE TABLE Recepsping (
......
    Datee datetime NOT NULL default "1901-01-01 00:00:00",
......
```

### CODE REVIEW

**Comment by isedwards** [comment]
Thank you @faysal-ishtiaq. MCH users are using MySQL 5.1 which allows the dummy dates by default as an alternative to `NULL`.

The `NO_ZERO_DATE` [SQL Mode](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-setting) was added in MySQL 5.7.8.

Could you try:
1. Dropping the database
2. Setting `NO_ZERO_DATE` to False to allow the dummy default dates and restoring the schema
3. Run sqlacodegen again and checking it doesn't have any problem with the dummy date
4. Add a commit with this minor change

**Comment by faysal-ishtiaq** [comment]
Executing these commands resolved the issue with original DDL file.
```bash
mysql -h localhost -P 3306 --protocol tcp -D mch -u root -p
```

```sql
SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
exit;
```
```bash
mysql -h localhost -P 3306 --protocol tcp -D mch -u root -p < ./opencdms-test-data/schemas/mch/Create_MCH_English_basic_tables.sql
```

and from this package root
```bash
 sqlacodegen mysql+pymysql://root:root@localhost/mch > ./opencdms/models/mch/english.py
```

P.S: I used latest MySQL docker image

**Review by isedwards — APPROVED** [review]

**Comment by isedwards** [comment]
@cla-bot check

**Comment by isedwards** [comment]
Resolves #10

**Pull request merged**
